//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wintest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STIs { get; set; }
        public virtual DbSet<STK> STKs { get; set; }
    
        public virtual ObjectResult<string> arama(string arama)
        {
            var aramaParameter = arama != null ?
                new ObjectParameter("arama", arama) :
                new ObjectParameter("arama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("arama", aramaParameter);
        }
    
        public virtual ObjectResult<listeleme_Result> listeleme(string arama, Nullable<int> baslangictarihi, Nullable<int> bitistarihi)
        {
            var aramaParameter = arama != null ?
                new ObjectParameter("arama", arama) :
                new ObjectParameter("arama", typeof(string));
    
            var baslangictarihiParameter = baslangictarihi.HasValue ?
                new ObjectParameter("baslangictarihi", baslangictarihi) :
                new ObjectParameter("baslangictarihi", typeof(int));
    
            var bitistarihiParameter = bitistarihi.HasValue ?
                new ObjectParameter("bitistarihi", bitistarihi) :
                new ObjectParameter("bitistarihi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listeleme_Result>("listeleme", aramaParameter, baslangictarihiParameter, bitistarihiParameter);
        }
    }
}
